blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/zmqEa4keCk
    about: For support that does not fit the GitHub issue format, please use Discord.
